## Task 1: Flipkart Price Sequence Dataset and LSTM Input

In [20]:
import numpy as np

prices = np.array([999, 1049, 1099, 1079, 1149, 1199, 1249, 1229, 1299, 1349], dtype=float)

X = []
y = []

for i in range(len(prices) - 3):
    X.append(prices[i:i+3])
    y.append(prices[i+3])


X = np.array(X)
y = np.array(y)

X = X.reshape((X.shape[0], X.shape[1], 1))

print("Price sequence:", prices)
print("X shape:", X.shape)
print("y shape:", y.shape)
print("X:")
print(X)
print("y:")
print(y)

Price sequence: [ 999. 1049. 1099. 1079. 1149. 1199. 1249. 1229. 1299. 1349.]
X shape: (7, 3, 1)
y shape: (7,)
X:
[[[ 999.]
  [1049.]
  [1099.]]

 [[1049.]
  [1099.]
  [1079.]]

 [[1099.]
  [1079.]
  [1149.]]

 [[1079.]
  [1149.]
  [1199.]]

 [[1149.]
  [1199.]
  [1249.]]

 [[1199.]
  [1249.]
  [1229.]]

 [[1249.]
  [1229.]
  [1299.]]]
y:
[1079. 1149. 1199. 1249. 1229. 1299. 1349.]


### Task 2: LSTM Model for Flipkart Price Prediction

In [26]:
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

prices = np.array([999, 1049, 1099, 1079, 1149, 1199, 1249, 1229, 1299, 1349], dtype=float)

X = []
y = []

for i in range(len(prices) - 3):
    X.append(prices[i:i+3])
    y.append(prices[i+3])


X = np.array(X)
y = np.array(y)

X = X.reshape((X.shape[0], X.shape[1], 1))

model = Sequential([LSTM(32, input_shape=(3,1)), Dense(1)]) 

model.compile(optimizer="adam", loss="mse")
history = model.fit(X, y, epochs=10, verbose=1) 

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 1503059.0000
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 1503036.0000
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1503012.6250
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 1502988.2500
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1502962.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 1502930.6250
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 1502889.0000
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1502830.2500
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1502754.8750
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1502682.0000


## Task 3: Predict Next Flipkart Price

In [36]:
last_sequence = np.array([1199, 1249, 1229], dtype=float)
last_sequence = last_sequence.reshape((1, 3, 1))

predicted_price = model.predict(last_sequence)

actual_price = 1299

print("Pridicted Price:", predicted_price[0][0])
print("Actual Price:", actual_price)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
Pridicted Price: -1.0908237
Actual Price: 1299


## Task 4: GRU Model and Training Time Comparison

In [49]:
import time 
import numpy as np 
import tensorflow as tf 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense

gru_model = Sequential([GRU(32, input_shape=(3,1)), Dense(1)])
gru_model.compile(optimizer="adam", loss="mse")

start_time = time.time()
gru_history = gru_model.fit(X, y, epochs=10, verbose=1)

lstm_training_time = time.time() - start_time
gru_training_time = time.time() - start_time

gru_prediction = gru_model.predict(last_sequence)

print("LSTM Training Time:", lstm_training_time, "seconds")
print("GRU Training Time:", gru_training_time, "seconds")
print("LSTM Prediction:", predicted_price[0][0])
print("GRU Prediction:", gru_prediction[0][0])
print("Actual Price:", actual_price)

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 1496522.8750
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 1496472.0000
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 1496417.3750
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 1496354.8750
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 1496277.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1496176.8750
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 1496065.3750
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 1495978.3750
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1495919.3750
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 1495867.6250
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 217ms/step
LSTM Training Time: 2.5541064739227295 seconds
GRU Training Time: 2.5541388988494873 seconds
LSTM Prediction: -1.0908237
GRU Prediction: 1.6948694
Actual Price: 1299


## Task 5: General Sequence Preparation Function for LSTM

In [59]:
import numpy as np 

def prepare_lstm_data(sequence, time_steps=3):
    sequence = np.array(sequence, dtype=float)

    X = []
    y = []

    for i in range(len(sequence) - time_steps):
        X.append(sequence[i:i + time_steps])
        y.append(sequence[i + time_steps])

    X = np.array(X)
    y = np.array(y)

    X = X.reshape((X.shape[0], X.shape[1], 1))

    return X, y

spotify_plays = [120, 145, 160, 180, 175, 200, 220, 240]

X, y = prepare_lstm_data(spotify_plays, time_steps=3)

print("X shape:", X.shape)
print("y shape:", y.shape)
print("X:")
print(X)
print("y:")
print(y)

X shape: (5, 3, 1)
y shape: (5,)
X:
[[[120.]
  [145.]
  [160.]]

 [[145.]
  [160.]
  [180.]]

 [[160.]
  [180.]
  [175.]]

 [[180.]
  [175.]
  [200.]]

 [[175.]
  [200.]
  [220.]]]
y:
[180. 175. 200. 220. 240.]
